# Generated by Django 5.2.15 on 2026-06-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=12)),
                ('assistant_id', models.CharField(blank=True, max_length=100)),
                ('from_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('max_concurrent_calls', models.PositiveIntegerField(default=5)),
                ('calls_per_minute', models.PositiveIntegerField(default=10)),
                ('max_attempts', models.PositiveIntegerField(default=2)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('done', 'Done'), ('failed', 'Failed (retryable)'), ('exhausted', 'Exhausted')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='leads.lead')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignLead', to='leads.lead'),
        ),
        migrations.AddConstraint(
            model_name='campaignlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'lead'), name='uniq_campaign_lead'),
        ),
    ]
