# Generated by Django 5.2.15 on 2026-06-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('raw_phone', models.CharField(blank=True, max_length=50)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('csv', 'CSV upload'), ('manual', 'Manual entry')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'phone_e164'), name='uniq_org_phone')],
            },
        ),
    ]
