# Generated by Django 5.2.15 on 2026-06-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vapi_call_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In progress'), ('ended', 'Ended'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=100)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('structured_outcome', models.JSONField(blank=True, default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('raw_end_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='campaigns.campaignlead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
