# Generated by Django 5.2.15 on 2026-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Organization', max_length=200)),
                ('vapi_credential_id', models.CharField(blank=True, max_length=100)),
                ('vapi_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('vapi_assistant_id', models.CharField(blank=True, max_length=100)),
                ('default_caller_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
