# Generated by Django 5.2.15 on 2026-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_voice_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_voice_provider',
            field=models.CharField(blank=True, default='vapi', max_length=40),
        ),
    ]
